version: '3'
services:
  stock_market_charting-mysql:
    image: mysql:8.0.18
    ports:
      - "33061:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pass@word1
    volumes:
      - ./stock_market_chartingdb:/var/lib/mysql
      - ./dbscripts:/docker-entrypoint-initdb.d
      
  eureka-discovery-server:
    image: eureka-discovery-app
    build: ./mid-tier/eureka-discovery-server/.
    ports:
      - 8761:8761
      
  upload-excel-service:
    image: upload-excel-service-app
    build: ./mid-tier/upload-excel-service/.
    ports:
      - 8092:8092
    depends_on:
      - stock_market_charting-mysql
      - eureka-discovery-server
    links:
      - stock_market_charting-mysql
      - eureka-discovery-server

  authentication-service:
    image: authentication-app
    build: ./mid-tier/authentication-service/.
    ports:
      - 8091:8091
    depends_on:
      - stock_market_charting-mysql
      - eureka-discovery-server
    links:
      - stock_market_charting-mysql
      - eureka-discovery-server
      
  zuul-gateway:
    image: zuul-gateway-app
    build: ./mid-tier/zuul-gateway/.
    ports:
      - 8083:8083   
            
  stockmarket-app:
    image: stock-webapp
    build: ./front-end/stock-webapp/dist/.
    ports:
      - 4200:80
    links:
      - zuul-gateway 
       